# -*- coding: utf-8 -*-
# Deployment settings for DrawSprite_Iw2D.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/6.2/s3e/makefile_builder/mkb.py', 'c:/Users/Daniel/Documents/DrawSprite_Iw2D/DrawSprite_Iw2D/DrawSprite_Iw2D.mkb', '--deploy-only']
mkb = 'c:/Users/Daniel/Documents/DrawSprite_Iw2D/DrawSprite_Iw2D/DrawSprite_Iw2D.mkb'
mkf = ['c:\\marmalade\\6.2\\modules\\iw2d\\iw2d.mkf', 'c:\\marmalade\\6.2\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\6.2\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\6.2\\modules\\iwutil\\iwutil.mkf', u'c:\\users\\daniel\\appdata\\roaming\\marmalade\\packages\\6.2.0\\libjpeg_6b\\libjpeg.mkf', u'c:\\users\\daniel\\appdata\\roaming\\marmalade\\packages\\6.2.0\\libpng_1.2.34\\libpng.mkf', u'c:\\users\\daniel\\appdata\\roaming\\marmalade\\packages\\6.2.0\\zlib_1.2.4\\zlib.mkf', 'c:\\marmalade\\6.2\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\6.2\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\6.2\\modules\\iwgxfont\\iwgxfont.mkf', u'c:\\users\\daniel\\appdata\\roaming\\marmalade\\packages\\6.2.0\\tiniconv_1.0.1\\tiniconv.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/Daniel/Documents/DrawSprite_Iw2D/DrawSprite_Iw2D/data/test1.png', 'test1.png', 0),
    ('c:/Users/Daniel/Documents/DrawSprite_Iw2D/DrawSprite_Iw2D/data/test2.png', 'test2.png', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'DrawSprite_Iw2D'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'DrawSprite_Iw2D'
    long_caption = 'DrawSprite_Iw2D'
    version = [0, 0, 1]
    config = ['c:/Users/Daniel/Documents/DrawSprite_Iw2D/DrawSprite_Iw2D/data/app.icf']
    data_dir = 'c:/Users/Daniel/Documents/DrawSprite_Iw2D/DrawSprite_Iw2D/data'
    iphone_link_lib = []
    linux_ext_lib = []
    iphone_link_libdir = []
    iphone_link_opts = []
    osx_ext_dll = []
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    android_extra_application_manifest = []
    win32_ext_dll = []
    android_so = []
    iphone_link_libs = []
    target = {
         'arm' : {
                   'debug'   : r'c:/Users/Daniel/Documents/DrawSprite_Iw2D/DrawSprite_Iw2D/build_drawsprite_iw2d_vc9/Debug_DrawSprite_Iw2D_VC9_arm/DrawSprite_Iw2D.s3e',
                   'release' : r'c:/Users/Daniel/Documents/DrawSprite_Iw2D/DrawSprite_Iw2D/build_drawsprite_iw2d_vc9/Release_DrawSprite_Iw2D_VC9_arm/DrawSprite_Iw2D.s3e',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Users/Daniel/Documents/DrawSprite_Iw2D/DrawSprite_Iw2D/build_drawsprite_iw2d_vc9/Debug_DrawSprite_Iw2D_VC9_gcc_mips/DrawSprite_Iw2D.so',
                   'release' : r'c:/Users/Daniel/Documents/DrawSprite_Iw2D/DrawSprite_Iw2D/build_drawsprite_iw2d_vc9/Release_DrawSprite_Iw2D_VC9_gcc_mips/DrawSprite_Iw2D.so',
                 },
         'x86' : {
                   'debug'   : r'c:/Users/Daniel/Documents/DrawSprite_Iw2D/DrawSprite_Iw2D/build_drawsprite_iw2d_vc9/Debug_DrawSprite_Iw2D_VC9_x86/DrawSprite_Iw2D.s86',
                   'release' : r'c:/Users/Daniel/Documents/DrawSprite_Iw2D/DrawSprite_Iw2D/build_drawsprite_iw2d_vc9/Release_DrawSprite_Iw2D_VC9_x86/DrawSprite_Iw2D.s86',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Users/Daniel/Documents/DrawSprite_Iw2D/DrawSprite_Iw2D/build_drawsprite_iw2d_vc9/Debug_DrawSprite_Iw2D_VC9_gcc_arm/DrawSprite_Iw2D.s3e',
                   'release' : r'c:/Users/Daniel/Documents/DrawSprite_Iw2D/DrawSprite_Iw2D/build_drawsprite_iw2d_vc9/Release_DrawSprite_Iw2D_VC9_gcc_arm/DrawSprite_Iw2D.s3e',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
